---
- name: Converge
  hosts: all
  become: true
  vars:
    molecule_is_test: true
    rke2_server: "{{ lookup('file', 'rke2_server.yml') | from_yaml }}"
    rke2_agent: "{{ lookup('file', 'rke2_agent.yml') | from_yaml }}"
    rke2_airgap: true
    rke2_release_version: latest
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
