---
- name: Prepare
  hosts: node*
  become: true
  tasks:
    - name: Ensure apt cache is updated and iptables is installed
      ansible.builtin.apt:
        name: iptables
        state: present
        update_cache: true
      when: ansible_pkg_mgr == 'apt'

    - name: Ensure install directory and configuration directory exists
      ansible.builtin.file:
        path: "/opt/rke2/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - bin
        - etc

    - name: Ensure data directory exists
      ansible.builtin.file:
        path: "/var/lib/rke2-io"
        state: directory
        mode: 0755
