---

- name: Ensure systemd context is correct if we are running rke2 rootless
  ansible.builtin.set_fact:
    rke2_systemd_context: user
    rke2_systemd_unit_dir: "{{ ansible_user_dir }}/.config/systemd/user"
  when:
    - rke2_runtime_config is defined
    - rke2_runtime_config.rootless is defined
    - rke2_runtime_config.rootless
