---

- name: Ensure that the manifests directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ rke2_server_manifests_dir }}"
    mode: 0755
  when: >-
    rke2_primary_control_node and
    (rke2_server_manifests_templates | length > 0
    or rke2_server_manifests_urls | length > 0)
  become: "{{ rke2_become }}"

- name: Ensure that the pod-manifests directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ rke2_server_pod_manifests_dir }}"
    mode: 0755
  when: >-
    rke2_control_node and
    (rke2_server_pod_manifests_templates | length > 0
    or rke2_server_pod_manifests_urls | length > 0)
  become: "{{ rke2_become }}"

# https://rancher.com/docs/rke2/latest/en/advanced/#auto-deploying-manifests
- name: Ensure auto-deploying manifests are copied to the primary controller
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_server_manifests_dir }}/{{ item | basename | replace('.j2', '') }}"
    mode: 0644
  loop: "{{ rke2_server_manifests_templates }}"
  become: "{{ rke2_become }}"
  when:
    - rke2_primary_control_node
    - rke2_server_manifests_templates | length > 0

- name: Ensure auto-deploying manifests are downloaded to the primary controller
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ rke2_server_manifests_dir }}/{{ item.filename | default(item.url | basename) }}"
    mode: 0644
  loop: "{{ rke2_server_manifests_urls }}"
  become: "{{ rke2_become }}"
  when:
    - rke2_primary_control_node
    - not ansible_check_mode
    - rke2_server_manifests_urls | length > 0

- name: Ensure static pod manifests are copied to controllers
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_server_pod_manifests_dir }}/{{ item | basename | replace('.j2', '') }}"
    mode: 0644
  loop: "{{ rke2_server_pod_manifests_templates }}"
  become: "{{ rke2_become }}"
  when:
    - rke2_control_node

# https://rancher.com/docs/rke2/latest/en/advanced/#auto-deploying-manifests
- name: Ensure auto-deploying manifests are downloaded to the primary controller
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ rke2_server_pod_manifests_dir }}/{{ item.filename | default(item.url | basename) }}"
    mode: 0644
  loop: "{{ rke2_server_pod_manifests_urls }}"
  become: "{{ rke2_become }}"
  when:
    - rke2_control_node
    - not ansible_check_mode
