---

- name: Ensure rke2_build_cluster is false if running against a single node.
  ansible.builtin.set_fact:
    rke2_build_cluster: false
  when:
    - ansible_play_hosts | length < 2
    - rke2_registration_address is not defined

- name: Ensure rke2 control node fact is set
  ansible.builtin.set_fact:
    rke2_control_node: "{{ not rke2_build_cluster }}"
  when: rke2_control_node is not defined

- name: Ensure rke2 primary control node fact is set
  ansible.builtin.set_fact:
    rke2_primary_control_node: "{{ not rke2_build_cluster }}"
  when: rke2_primary_control_node is not defined

- name: Ensure rke2 control plane port is captured
  ansible.builtin.set_fact:
    rke2_control_plane_port: "{{ rke2_runtime_config['https-listen-port'] | default(6443) }}"
  delegate_to: rke2_primary_control_node

- name: Ensure rke2 node IP is configured when node-ip is defined
  ansible.builtin.set_fact:
    rke2_node_ip: "{{ rke2_runtime_config['node-ip'] }}"
  when:
    - rke2_runtime_config['node-ip'] is defined

- name: Ensure a count of control nodes is generated from ansible_play_hosts
  ansible.builtin.set_fact:
    rke2_controller_list: "{{ rke2_controller_list + [item] }}"
  when:
    - hostvars[item].rke2_control_node is defined
    - hostvars[item].rke2_control_node
  loop: "{{ ansible_play_hosts }}"

- name: Ensure a rke2 control node is defined if none are found in ansible_play_hosts
  when:
    - rke2_controller_list | length < 1
    - rke2_build_cluster is defined
    - rke2_build_cluster
  block:
    - name: Set the control host
      ansible.builtin.set_fact:
        rke2_control_node: true
      when: inventory_hostname == ansible_play_hosts[0]

    - name: Ensure a count of control nodes is generated
      ansible.builtin.set_fact:
        rke2_controller_list: "{{ rke2_controller_list + [item] }}"
      when:
        - hostvars[item].rke2_control_node is defined
        - hostvars[item].rke2_control_node
      loop: "{{ ansible_play_hosts }}"

- name: Ensure a primary rke2 control node is defined if multiple are found in ansible_play_hosts
  ansible.builtin.set_fact:
    rke2_primary_control_node: true
  when:
    - rke2_controller_list is defined
    - inventory_hostname == rke2_controller_list[0]
    - rke2_build_cluster is defined
    - rke2_build_cluster

- name: Ensure ansible_host is mapped to inventory_hostname
  ansible.builtin.blockinfile:
    path: /tmp/inventory.txt
    block: |
      {% for host in ansible_play_hosts %}
      {% filter replace('\n', ' ') %}
      {{ host }}
      @@@
      {{ hostvars[host].ansible_host | default(hostvars[host].ansible_fqdn) | string }}
      @@@
      C_{{ hostvars[host].rke2_control_node | string }}
      @@@
      P_{{ hostvars[host].rke2_primary_control_node | default(False) | string }}
      {% endfilter %}
      @@@ END:{{ host }}
      {% endfor %}
    create: true
    mode: 0600
  check_mode: false
  when: rke2_control_node is defined

- name: Delegate an initializing control plane node
  when: rke2_registration_address is not defined
        or rke2_control_delegate is not defined
  block:
    - name: Lookup control node from file
      ansible.builtin.command:
        cmd: "grep -i '{{ 'P_True' if (rke2_controller_list | length > 1) else 'C_True' }}' /tmp/inventory.txt"
      changed_when: false
      check_mode: false
      register: rke2_control_delegate_raw

    - name: Ensure control node is delegated for obtaining a cluster token
      ansible.builtin.set_fact:
        rke2_control_delegate: "{{ rke2_control_delegate_raw.stdout.split(' @@@ ')[0] }}"
      check_mode: false
      when: rke2_control_delegate is not defined

    - name: Ensure the node registration address is defined from rke2_control_node_address
      ansible.builtin.set_fact:
        rke2_registration_address: "{{ rke2_control_node_address }}"
      check_mode: false
      when: rke2_control_node_address is defined

    - name: Ensure the node registration address is defined from node-ip
      ansible.builtin.set_fact:
        rke2_registration_address: "{{ hostvars[rke2_control_delegate].rke2_node_ip }}"
      check_mode: false
      when:
        - rke2_registration_address is not defined
        - rke2_control_node_address is not defined
        - hostvars[rke2_control_delegate].rke2_node_ip is defined

    - name: Ensure the node registration address is defined
      ansible.builtin.set_fact:
        rke2_registration_address: "{{ hostvars[rke2_control_delegate].ansible_host | default(hostvars[rke2_control_delegate].ansible_fqdn) }}"
      check_mode: false
      when:
        - rke2_registration_address is not defined
        - rke2_control_node_address is not defined
