---

- name: Check to see if rke2-killall.sh exits
  ansible.builtin.stat:
    path: /usr/local/bin/rke2-killall.sh
  register: check_rke2_killall_script

- name: Check to see if rke2-uninstall.sh exits
  ansible.builtin.stat:
    path: /usr/local/bin/rke2-uninstall.sh
  register: check_rke2_uninstall_script

- name: Run rke2-killall.sh
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2-killall.sh
  register: rke2_killall
  changed_when: rke2_killall.rc == 0
  when: check_rke2_killall_script.stat.exists
  become: "{{ rke2_become }}"

- name: Run rke2-uninstall.sh
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2-uninstall.sh
  args:
    removes: /usr/local/bin/rke2-uninstall.sh
  register: rke2_uninstall
  changed_when: rke2_uninstall.rc == 0
  when: check_rke2_uninstall_script.stat.exists
  become: "{{ rke2_become }}"

- name: Ensure hard links are removed
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/{{ item }}"
    state: absent
  loop:
    - kubectl
    - crictl
    - ctr
  when:
    - rke2_install_hard_links
    - not ansible_check_mode
  become: "{{ rke2_become }}"
