---

- name: Check if kubectl exists
  ansible.builtin.stat:
    path: "{{ rke2_install_dir }}/kubectl"
  register: rke2_check_kubectl
  become: "{{ rke2_become }}"

- name: Clean up nodes that are in an uninstalled state
  when:
    - rke2_check_kubectl.stat.exists is defined
    - rke2_check_kubectl.stat.exists
    - rke2_control_delegate is defined
    - not ansible_check_mode
  block:
    - name: Gather a list of nodes
      ansible.builtin.command:
        cmd: "{{ rke2_install_dir }}/kubectl get nodes"
      changed_when: false
      failed_when: false
      delegate_to: "{{ rke2_control_delegate }}"
      run_once: true
      register: kubectl_get_nodes_result
      become: "{{ rke2_become }}"

    - name: Ensure uninstalled nodes are drained # noqa no-changed-when
      ansible.builtin.command:
        cmd: >-
          {{ rke2_install_dir }}/kubectl drain {{ item }}
            --ignore-daemonsets
            --{{ rke2_drain_command[ansible_version.string is version_compare('1.22', '>=')] }}
            --force
      delegate_to: "{{ rke2_control_delegate }}"
      run_once: true
      when:
        - kubectl_get_nodes_result.stdout is defined
        - item in kubectl_get_nodes_result.stdout
        - hostvars[item].rke2_state is defined
        - hostvars[item].rke2_state == 'uninstalled'
      loop: "{{ ansible_play_hosts }}"
      become: "{{ rke2_become }}"

    - name: Ensure uninstalled nodes are removed # noqa no-changed-when
      ansible.builtin.command:
        cmd: "{{ rke2_install_dir }}/kubectl delete node {{ item }}"
      delegate_to: "{{ rke2_control_delegate }}"
      run_once: true
      when:
        - kubectl_get_nodes_result.stdout is defined
        - item in kubectl_get_nodes_result.stdout
        - hostvars[item].rke2_state is defined
        - hostvars[item].rke2_state == 'uninstalled'
      loop: "{{ ansible_play_hosts }}"
      become: "{{ rke2_become }}"
