---

- name: Ensure rke2 control plane server is started
  ansible.builtin.systemd:
    name: rke2
    state: started
    enabled: "{{ rke2_start_on_boot }}"
    scope: "{{ rke2_systemd_context }}"
  register: rke2_systemd_start_rke2
  until: rke2_systemd_start_rke2 is succeeded
  retries: 3
  delay: 3
  failed_when:
    - rke2_systemd_start_rke2 is not succeeded
    - not ansible_check_mode
  become: "{{ rke2_become }}"
