---

- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: 0755

- name: Ensure rke2 binary is copied from controller to target host
  ansible.builtin.copy:
    src: rke2
    # TODO: allow airgap to bypass version post-fix
    dest: "{{ rke2_install_dir }}/rke2-{{ rke2_release_version }}"
    mode: 0755
  become: "{{ rke2_become }}"
