---

- name: Ensure that the config.yaml.d directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ rke2_config_yaml_d_dir }}"
    mode: 0755
  when: >-
    rke2_server_config_yaml_d_files | length > 0
    or rke2_agent_config_yaml_d_files | length > 0
  become: "{{ rke2_become }}"

- name: Ensure configuration files are copied to controllers
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_config_yaml_d_dir }}/{{ item | basename | replace('.j2', '') }}"
    mode: 0644
  loop: "{{ rke2_server_config_yaml_d_files }}"
  become: "{{ rke2_become }}"
  when: rke2_control_node

- name: Ensure configuration files are copied to agents
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_config_yaml_d_dir }}/{{ item | basename | replace('.j2', '') }}"
    mode: 0644
  loop: "{{ rke2_agent_config_yaml_d_files }}"
  become: "{{ rke2_become }}"
  when: not rke2_control_node
