---

- name: Ensure directories exist
  ansible.builtin.include_tasks: ensure_directories.yml
  loop: "{{ rke2_ensure_directories_exist }}"
  loop_control:
    loop_var: directory

- name: Ensure installed node
  ansible.builtin.include_tasks: ensure_installed_node.yml
  when:
    - ((rke2_control_node and rke2_controller_list | length == 1)
        or (rke2_primary_control_node and rke2_controller_list | length > 1))
    - not ansible_check_mode

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure installed node | rke2_build_cluster
  ansible.builtin.include_tasks: ensure_installed_node.yml
  when: rke2_build_cluster

- name: Determine if the systems are already clustered
  ansible.builtin.stat:
    path: "{{ rke2_token_location }}"
  register: rke2_token_cluster_check

- name: Ensure control plane started with {{ ansible_service_mgr }}
  ansible.builtin.include_tasks: ensure_control_plane_started_{{ ansible_service_mgr }}.yml
  when: (rke2_control_node and rke2_controller_list | length == 1)
        or (rke2_primary_control_node and rke2_controller_list | length > 1)
        or rke2_token_cluster_check.stat.exists
