---

- name: Ensure containerd registries file exists
  ansible.builtin.template:
    src: registries.yaml.j2
    dest: "{{ rke2_config_dir }}/registries.yaml"
    mode: 0600
  notify:
    - "Reload {{ rke2_service_handler[ansible_service_mgr] }}"
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"
