---

- name: Ensure rke2 service is started
  ansible.builtin.systemd:
    name: rke2
    state: started
    enabled: "{{ rke2_start_on_boot }}"
  when: rke2_non_root is not defined or not rke2_non_root
  become: "{{ rke2_become }}"

- name: Ensure rke2 service is started
  ansible.builtin.systemd:
    name: rke2
    state: started
    enabled: "{{ rke2_start_on_boot }}"
    scope: user
  when:
    - rke2_non_root is defined
    - rke2_non_root
  become: "{{ rke2_become }}"
