---

- name: Ensure rke2 is linked into the installation destination
  ansible.builtin.file:
    src: "{{ rke2_install_dir }}/rke2-{{ rke2_release_version }}"
    dest: "{{ rke2_install_dir }}/{{ item }}"
    state: "{{ 'hard' if rke2_install_hard_links else 'link' }}"
    force: "{{ rke2_install_hard_links }}"
    mode: 0755
  loop:
    - rke2
    - kubectl
    - crictl
    - ctr
  when: not ansible_check_mode
  notify:
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"

- name: Ensure rke2 config file exists
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ rke2_config_file }}"
    mode: 0644
  notify:
    - "Reload {{ rke2_service_handler[ansible_service_mgr] }}"
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"

- name: Ensure cluster token is present when pre-defined
  when: rke2_control_token is defined
  block:
    - name: Ensure the cluster token file location exists
      ansible.builtin.file:
        path: "{{ rke2_token_location | dirname }}"
        state: directory
        mode: 0755
      become: "{{ rke2_become }}"

    - name: Ensure rke2 cluster token file is present
      ansible.builtin.template:
        src: cluster-token.j2
        dest: "{{ rke2_token_location }}"
        mode: 0600
      become: "{{ rke2_become }}"
      notify:
        - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"

- name: Ensure rke2 service unit file is present
  ansible.builtin.template:
    src: rke2.service.j2
    dest: "{{ rke2_systemd_unit_dir }}/rke2.service"
    mode: 0644
  when:
    - rke2_service_handler[ansible_service_mgr] == 'systemd'
  notify:
    - "Reload {{ rke2_service_handler[ansible_service_mgr] }}"
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"

- name: Ensure rke2 service file is present
  ansible.builtin.template:
    src: rke2.openrc.j2
    dest: "{{ rke2_openrc_service_dir }}/rke2"
    mode: 0744
  when:
    - rke2_service_handler[ansible_service_mgr] == 'service'
  notify:
    - "Reload {{ rke2_service_handler[ansible_service_mgr] }}"
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"

- name: Ensure rke2 logrotate file is present
  ansible.builtin.template:
    src: rke2.logrotate.j2
    dest: "{{ rke2_logrotate_dir }}/rke2"
    mode: 0640
  when:
    - rke2_service_handler[ansible_service_mgr] == 'service'
  notify:
    - "Reload {{ rke2_service_handler[ansible_service_mgr] }}"
    - "Restart rke2 {{ rke2_service_handler[ansible_service_mgr] }}"
  become: "{{ rke2_become }}"

- name: Ensure rke2 killall script is present
  ansible.builtin.template:
    src: rke2-killall.sh.j2
    dest: "/usr/local/bin/rke2-killall.sh"
    mode: 0700
  become: "{{ rke2_become }}"
  when:
    - rke2_runtime_config is defined
    - ("rootless" not in rke2_runtime_config or not rke2_runtime_config.rootless)

- name: Ensure rke2 uninstall script is present
  ansible.builtin.template:
    src: rke2-uninstall.sh.j2
    dest: "/usr/local/bin/rke2-uninstall.sh"
    mode: 0700
  become: "{{ rke2_become }}"
  when:
    - rke2_runtime_config is defined
    - ("rootless" not in rke2_runtime_config or not rke2_runtime_config.rootless)
