---

- name: Run pre-checks
  ansible.builtin.import_tasks: pre_checks.yml

- name: Ensure state {{ (rke2_state | lower) | default('installed') }}
  ansible.builtin.include_tasks: state_{{ (rke2_state | lower) | default('installed') }}.yml
