---

- name: Check that rke2 is not running
  ansible.builtin.command:
    cmd: pgrep rke2
  failed_when:
    - check_rke2_process.rc == 0
    - not ansible_check_mode
  changed_when: false
  register: check_rke2_process

- name: Fail if rke2 binaries have not been removed
  ansible.builtin.stat:
    path: "{{ rke2_install_dir }}/{{ item }}"
  register: check_rke2_binaries_removed
  failed_when: check_rke2_binaries_removed.stat.exists
  loop:
    - rke2
    - kubectl
    - crictl
    - ctr

- name: Check rke2-killall.sh is removed
  ansible.builtin.stat:
    path: /usr/local/bin/rke2-killall.sh
  register: check_rke2_killall

- name: Fail if rke2-killall.sh script still exists
  ansible.builtin.fail:
    msg: rke2-killall.sh still exists, uninstall script failed. Please investigate.
  when: check_rke2_killall.stat.exists

- name: Check rke2-uninstall.sh is removed
  ansible.builtin.stat:
    path: /usr/local/bin/rke2-uninstall.sh
  register: check_rke2_uninstall

- name: Fail if rke2-uninstall.sh script still exists
  ansible.builtin.fail:
    msg: rke2-uninstall.sh is still exists, uninstall script failed. Please investigate.
  when: check_rke2_uninstall.stat.exists
