---

- name: Check that all nodes to be ready
  ansible.builtin.command:
    cmd: "{{ rke2_install_dir }}/kubectl get nodes"
  changed_when: false
  failed_when: >-
    kubectl_get_nodes_result.stdout.find("was refused") != -1 or
    kubectl_get_nodes_result.stdout.find("ServiceUnavailable") != -1
  register: kubectl_get_nodes_result
  until:
    - kubectl_get_nodes_result.rc == 0
    - kubectl_get_nodes_result.stdout.find("NotReady") == -1
  retries: 30
  delay: 5
  when:
    - rke2_control_node
    - ("flannel-backend" not in rke2_runtime_config
       or rke2_runtime_config["flannel-backend"] != "none")
    - not ansible_check_mode
  become: "{{ rke2_become }}"
