---

- name: "Check that rke2_release_version >= {{ rke2_min_version }}"
  ansible.builtin.assert:
    that:
      - (rke2_release_version | replace('v', '')) is version_compare(rke2_min_version, '>=')
    success_msg: "{{ rke2_release_version }} is supported by this role."
    fail_msg: "{{ rke2_release_version }} is not supported by this role, please use prymalinstynct.rke2 v1.x."
  when: not rke2_airgap

- name: Check configuration in rke2_server and rke2_agent that needs alternate configuration
  ansible.builtin.assert:
    that:
      - (item.setting not in rke2_runtime_config)
    success_msg: "{{ item.setting }} not found in server/agent config"
    fail_msg: >-
      {{ item.setting }} found in server/agent config.
      Please set {{ item.correction }} to use this option.
      {% if item.document is defined %}
      Documentation: {{ item.documentation }}
      {% endif %}
  loop: "{{ rke2_config_exclude }}"

- name: Check configuration in rke2_server and rke2_agent for deprecated configuration
  ansible.builtin.assert:
    that:
      - (item.setting not in rke2_runtime_config)
        or (not rke2_runtime_config[item.setting])
    success_msg: "{{ item.setting }} not found in server/agent config"
    fail_msg: >-
      {{ item.setting }} found in server/agent config.
      Please set {{ item.correction }} to use this option.
      {% if item.document is defined %}
      Documentation: {{ item.documentation }}
      {% endif %}
  loop: "{{ rke2_deprecated_config }}"
  when:
    - not rke2_airgap
    - (item.when is not defined
       or (item.when is defined and (rke2_release_version | replace('v', '')) is version_compare(item.when, '>=')))
    - not rke2_use_unsupported_config

- name: Check configuration in rke2_server and rke2_agent against release version
  ansible.builtin.assert:
    that:
      - (rke2_release_version | replace('v', '')) is version_compare(item.version, '>=')
    success_msg: "{{ item.setting }} is supported by {{ rke2_release_version }}"
    fail_msg: >-
      {{ item.setting }} is not supported in {{ rke2_release_version }}.
      Please update to v{{ item.version }} to use this option.
      {% if item.document is defined %}
      Documentation: {{ item.documentation }}
      {% endif %}
  loop: "{{ rke2_config_version_check }}"
  when:
    - rke2_config_version_check is defined
    - item.setting in rke2_runtime_config
