---

- name: Check that {{ package.name }} is installed
  ansible.builtin.command:
    cmd: "which {{ package.name }}"
  changed_when: false
  failed_when: false
  register: check_rke2_required_package
  become: "{{ rke2_become }}"

- name: Test that checks for {{ package.name }} passed
  ansible.builtin.assert:
    that:
      - check_rke2_required_package.rc == 0
    success_msg: "Found required package: {{ package.name }}."
    fail_msg: >-
      Could not find package: {{ package.name }}.
      {% if package.documentation is defined %}
      Documentation: {{ package.documentation }}
      {% endif %}
  when:
    - check_rke2_required_package.rc is defined
    - (package.until is not defined
       or (rke2_release_version | replace('v', '')) is version_compare(package.until, '<'))
    - (package.from is not defined
       or (rke2_release_version | replace('v', '')) is version_compare(package.from, '>='))
