---

- name: Check if embedded etcd datastore is enabled and marked as experimental
  ansible.builtin.assert:
    that:
      - rke2_use_experimental is defined and rke2_use_experimental
    success_msg: "Experimental variables are defined and enabled."
    fail_msg: >-
      Experimental variable rke2_etcd_datastore has been configured.
      If you want to use this ensure you set rke2_use_experimental,
  when:
    - rke2_etcd_datastore is defined
    - rke2_etcd_datastore
    - (rke2_release_version | replace('v', '')) is version_compare("1.19.5", '<')

- name: Check if any experimental variables are configure and if they are enabled with rke2_use_experimental
  ansible.builtin.assert:
    that:
      - rke2_use_experimental is defined and rke2_use_experimental
    success_msg: "Experimental variables are defined and enabled."
    fail_msg: >-
      Experimental variable {{ item.setting }} has been configured.
      If you want to use this ensure you set rke2_use_experimental.
      {% if item.document is defined %}
      Documentation: {{ item.documentation }}
      {% endif %}
  loop: "{{ rke2_experimental_config }}"
  when:
    - (item.setting in rke2_runtime_config and rke2_runtime_config[item.setting])
    - ((item.until is not defined) or
        (item.until is defined and (rke2_release_version | replace('v', '')) is version_compare(item.until, '<')))
