---

- name: Check the conditions when a single controller is defined
  ansible.builtin.assert:
    that:
      - (rke2_controller_list | length == 1)
      - ("datastore-endpoint" not in rke2_runtime_config or not rke2_runtime_config['datastore-endpoint'])
      - (rke2_etcd_datastore is not defined or not rke2_etcd_datastore)
    success_msg: "Control plane configuration is valid."
    fail_msg: >-
      Control plane configuration is invalid.
      Please see notes about rke2_control_node and HA in README.md.
  when:
    - rke2_controller_list | length == 1
    - not rke2_use_unsupported_config
    - rke2_control_node

- name: Check the conditions when multiple controllers are defined
  ansible.builtin.assert:
    that:
      - (rke2_controller_list | length >= 2)
      - (("datastore-endpoint" in rke2_runtime_config and rke2_runtime_config['datastore-endpoint'])
          or (rke2_etcd_datastore is defined and rke2_etcd_datastore))
    success_msg: "Control plane configuration is valid."
    fail_msg: >-
      Control plane configuration is invalid. Please see notes about
      rke2_control_node and HA in README.md.
  when:
    - rke2_controller_list | length >= 2
    - rke2_control_node

- name: Check the conditions when embedded etcd is defined
  ansible.builtin.assert:
    that:
      - (rke2_controller_list | length >= 3)
      - (((rke2_controller_list | length) % 2) == 1)
    success_msg: "Control plane configuration is valid."
    fail_msg: >-
      Etcd should have a minimum of 3 defined members and the number of
      members should be odd. Please see notes about HA in README.md
  when:
    - rke2_etcd_datastore is defined
    - rke2_etcd_datastore
    - not rke2_use_unsupported_config
    - rke2_control_node
    - rke2_state != 'uninstalled'
