---

- name: Ensure rke2_release_version is set to default if false
  ansible.builtin.set_fact:
    rke2_release_version: "{{ rke2_release_channel }}"
  check_mode: false
  when:
    - rke2_release_version is defined
    - not rke2_release_version

- name: Ensure the default release channel is set
  ansible.builtin.set_fact:
    rke2_release_channel: "{{ rke2_release_version | default('stable') }}"
  check_mode: false

- name: "Get the latest release version from {{ rke2_api_releases }}"
  ansible.builtin.uri:
    url: "{{ rke2_api_releases }}"
    return_content: true
    body_format: json
  register: rke2_latest_release
  check_mode: false

- name: Ensure the release version is set as a fact
  ansible.builtin.set_fact:
    rke2_release_version: "{{ item.latest }}"
  loop: "{{ rke2_latest_release.json.data }}"
  check_mode: false
  when:
    - item.name == rke2_release_channel
    - item.type == "channel"
