---

- name: Check that the initial control plane server is available to accept connections
  ansible.builtin.wait_for:
    port: "{{ rke2_runtime_config['https-listen-port'] | default('6443') }}"
    host: "{{ rke2_runtime_config['bind-address'] | default('127.0.0.1') }}"
    delay: 5
    sleep: 5
    timeout: 300

- name: Check that cluster-token exists
  ansible.builtin.stat:
    path: "{{ rke2_runtime_config['data-dir'] | default(rke2_data_dir) }}/server/token"
  register: rke2_check_cluster_token
  check_mode: false
  failed_when:
    - not rke2_check_cluster_token.stat.exists
    - not ansible_check_mode
  become: "{{ rke2_become }}"
