---

- name: Ensure nodes are drained and removed
  ansible.builtin.import_tasks: ensure_drain_and_remove_nodes.yml

- name: Determine systemd context
  ansible.builtin.import_tasks: determine_systemd_context.yml

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Run rke2 binary download and install tasks
  ansible.builtin.import_tasks: ensure_downloads.yml
  when: not rke2_airgap

- name: Run rke2 binary upload tasks | rke2_airgap
  ansible.builtin.import_tasks: ensure_uploads.yml
  when: rke2_airgap

- name: Run auto-deploy manifests and pod manifests tasks
  ansible.builtin.import_tasks: ensure_rke2_auto_deploy.yml

- name: Ensure rke2 configuration files are copied to controllers and agents
  ansible.builtin.import_tasks: ensure_rke2_config_files.yml

- name: Run rke2 installation tasks
  ansible.builtin.import_tasks: ensure_installed.yml

- name: Ensure containerd registries
  ansible.builtin.include_tasks: ensure_containerd_registries.yml
  when:
    - (rke2_registries.mirrors | default(None)) != None or (rke2_registries.configs | default(None) != None)
    - ('rootless' not in rke2_runtime_config or not rke2_runtime_config.rootless)

- name: Run cluster pre-checks
  ansible.builtin.include_tasks: pre_checks_cluster.yml
  when:
    - rke2_control_delegate is defined
    - rke2_control_delegate == inventory_hostname

- name: Run rke2 cluster tasks
  ansible.builtin.import_tasks: ensure_cluster.yml
  when:
    - rke2_build_cluster is defined
    - rke2_build_cluster
    - rke2_registration_address is defined
