---

- name: Run version pre-checks
  ansible.builtin.import_tasks: pre_checks_version.yml
  when:
    - rke2_release_version is not defined or not rke2_release_version
    - not rke2_airgap

- name: Run rke2 binary download and install tasks
  ansible.builtin.import_tasks: ensure_downloads.yml
  when: not rke2_airgap

- name: Run rke2 binary upload tasks | rke2_airgap
  ansible.builtin.import_tasks: ensure_uploads.yml
  when: rke2_airgap
