---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: "{{ rke2_systemd_context }}"
  become: "{{ rke2_become }}"

- name: Reload service
  ansible.builtin.set_fact:
    rke2_service_reloaded: true
  become: "{{ rke2_become }}"

- name: Restart rke2 systemd
  ansible.builtin.systemd:
    name: rke2
    state: restarted
    scope: "{{ rke2_systemd_context }}"
    enabled: "{{ rke2_start_on_boot }}"
  retries: 3
  delay: 3
  register: rke2_systemd_restart_rke2
  failed_when:
    - rke2_systemd_restart_rke2 is not success
    - not ansible_check_mode
  become: "{{ rke2_become }}"

- name: Restart rke2 service
  ansible.builtin.service:
    name: rke2
    state: restarted
    enabled: "{{ rke2_start_on_boot }}"
  retries: 3
  delay: 3
  register: rke2_service_restart_rke2
  failed_when:
    - rke2_service_restart_rke2 is not success
    - not ansible_check_mode
  become: "{{ rke2_become }}"
