---

- name: Converge
  hosts: node*
  become: true
  vars:
    molecule_is_test: true
    rke2_registration_address: loadbalancer
    rke2_control_token: 55ba04e5-e17d-4535-9170-3e4245453f4d
    rke2_server:
      datastore-endpoint: "postgres://postgres:verybadpass@database:5432/postgres?sslmode=disable"
    # rke2_agent:
    #   snapshotter: native
    rke2_service_env_file: /tmp/rke2.env
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        rke2_control_node: true
      when: inventory_hostname in ['node2', 'node3']
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
