---
- name: Converge
  hosts: node1
  become: true
  become_user: rke2user
  vars:
    molecule_is_test: true
    rke2_use_experimental: true
    rke2_server:
      rootless: true
    rke2_agent:
      rootless: true
    rke2_install_dir: "/home/{{ ansible_user_id }}/bin"
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
