---
- name: Prepare
  hosts: node1
  become: true
  tasks:
    - name: Ensure a user group exists
      ansible.builtin.group:
        name: user
        state: present

    - name: Ensure a normal user exists
      ansible.builtin.user:
        name: rke2user
        group: user
        state: present

    - name: Ensure a normal user has bin directory
      ansible.builtin.file:
        path: /home/rke2user/bin
        state: directory
        owner: rke2user
        group: user
        mode: 0700
