---

- name: Converge
  hosts: node*
  become: true
  vars:
    molecule_is_test: true
    rke2_release_version: "v1.21"
    rke2_use_experimental: true
    rke2_etcd_datastore: true
    rke2_server:
      secrets-encryption: true
    rke2_agent:
      node-ip: "{{ ansible_default_ipv4.address }}"
      snapshotter: native
      selinux: "{{ ansible_os_family | lower == 'redhat' }}"
    rke2_skip_validation: "{{ rke2_service_handler[ansible_service_mgr] == 'service' }}"
    # rke2_skip_post_checks: "{{ ansible_os_family | lower == 'redhat' }}"
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        rke2_control_node: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
