---
- name: Converge
  hosts: all
  become: true
  vars:
    pyratlabs_issue_controller_dump: true
    # rke2_agent:
    #   snapshotter: native
  pre_tasks:
    - name: Ensure rke2_debug is set
      ansible.builtin.set_fact:
        rke2_debug: true
  roles:
    - prymalinstynct.rke2
